name: MLOps Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run ZenML pipeline
      run: |
        zenml pipeline run churn_prediction_pipeline
    - name: Dockerize and Deploy
      run: |
        docker build -t churn-app .
        docker run -p 8501:8501 churn-app
